version: "3.8"
services:
  mysql-db:
    image: mysql:8.0
    container_name: paykey-mysql
    platform: linux/x86_64 # Khusus Mac M1/M2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: paykey_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7
    container_name: paykey-redis
    command: ["redis-server", "--requirepass", "redispass"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  paykey-server:
    container_name: paykey-server
    # build:
    #   context: .
    #   dockerfile: paykey-server/Dockerfile
    image: very271391/paykey-server:latest
    ports:
      - "8080:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://paykey-mysql:3306/paykey_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_PROFILES_ACTIVE: prod
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redispass
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: adminpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      PAYKEY_SECURITY_AES_SECRET: "PayKeySuperSecretMasterKey2026"

volumes:
  mysql_data:

  redis_data: