spring:
  profiles:
    active: local
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/paykey_db?useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    defer-datasource-initialization: true
server:
  port: 8081
redis:
  host: localhost
  port: 6379
  password:
logging:
  level:
    com.linecorp.line: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

fido2:
  rp:
    id: 192.168.1.3          # <--- PENTING: Harus 'localhost' agar cocok dengan browser
    origin: http://192.168.1.3:3000 # <--- PENTING: URL Frontend Next.js Anda
    port: 3000             # Port Frontend
    name: Secure Paykey
    
app:
  origins: # Optional: also accepts web origins as an allowlist
    # - android:aaa-bbb
    # - ios:aaa-bbb
    - android:apk-key-hash-sha256:KNxFf9ASburnBecoqT/TtD1G7WxWoBTFY3RzkED2FB0
    # Web origins
    # - https://example.com
    # - https://staging.example.com
    # For local development only
    - http://192.168.1.3:3000
    - http://192.168.1.3:4000

